services:
  itsm-4me-bot:
    build: .
    container_name: itsm.mos.ru_4me_parser_bot
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./db:/app/db              # сохраняем подписчиков
      - ./last_check.json:/app/last_check.json
    networks:
      - botnet

networks:
  botnet:
    driver: bridge